# AWEXOME LABS
# Database Configuration

common: &common
  encoding: utf8
  adapter: mysql2
  username: root
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *common
  database: wosomp_dev

test:
  <<: *common
  database: wosomp_test

production:
  <<: *common
  database: wosomp_production
  host: database.production.server.com
  username: aw3X0me
  password: beAw3xom3
