#!/usr/bin/env ruby
#
# MySQL TERMINAL/CONSOLE
# Colin McCloskey
#
# Reads given database configuration and kicks off a mysql client
# connection to the described database service with full host name, user
# name, and database name in command-line. Includes password in shell
# output, so use over-the-shoulder caution (it's in your file tree, anyway,
# but you know)
#

config_file = File.join( File.dirname(__FILE__), "..", "config", "database.yml")
unless File.exist?(config_file)
  $stderr.puts "Rails database config file #{config_file} does not exist"
  exit 1
end

begin
  require "yaml"
  all_config = YAML.load(File.open(config_file))
  environments = all_config.keys
  environment = ARGV.shift || "development"
  config = all_config[environment]
rescue Exception => e
  $stderr.puts "Error reading database configuration from #{config_file}"
  $stderr.puts e.message
  exit 1
end

unless environments.include?(environment)
  $stderr.puts "Database config for environment \"#{environment}\" does not exist."
  $stderr.puts "To specify environment, use: #{__FILE__} [#{environments.join("|")}]\n\n"
  exit 1
end

puts "Connecting to #{environment} database.\nTo change environment, use: #{__FILE__} [#{environments.join("|")}]\n\n"

cli_opts = Hash.new
cli_opts["-u"] = config["username"] if config["username"]
cli_opts["-p"] = config["password"] if config["password"]
cli_opts["-h"] = config["host"] if config["host"]
cli_opts["-D"] = config["database"] if config["database"]
cmd = "mysql #{cli_opts.to_a.collect{|k,v| "#{k}#{v}"}.join(" ")}"
puts "Launching mysql: #{cmd}\n\n"
exec(cmd)
